<expression> ::= <additive_expression>
<additive_expression> ::= <additive_expression> <additive_operator> <multiplicative_expression> | <multiplicative_expression>
<multiplicative_expression> ::= <multiplicative_expression> <multiplicative_operator> <unary_expression> | <unary_expression>
<unary_expression> ::= <unary_operator> <unary_expression> | <postfix_expression>
<postfix_expression> ::= <postfix_expression> <postfix_operator> | <primary_expression>
<primary_expression> ::= <letter>+ | <number>+ | "(" <expression> ")" | <expression> "(" <expression> ("," <expression>)* ")"

<additive_operator> ::= "+" | "-"
<multiplicative_operator> ::= "*" | "/" | "%"
<unary_operator> ::= <additive_operator> | "!" | "~" | <postfix_operator>
<postfix_operator> ::= "++" | "--"

<letter> ::= [a-z] | [A-Z]
<number> ::= [0-9]